// Generated by tessera from a TypeScript kernel. Do not edit.
//
//   attention_f32   accumulate (m, d)   contract n
//   lanes m->y(2) d->x(1)   fragment 2   32 sequential steps
//   staged: v   workgroup 2048 B
//   no masks: every axis divides its block

@group(0) @binding(0) var<storage, read> q : array<f32>;
@group(0) @binding(1) var<storage, read> k : array<f32>;
@group(0) @binding(2) var<storage, read> v : array<f32>;
@group(0) @binding(3) var<storage, read_write> o : array<f32>;

var<workgroup> stage_v : array<f32, 512>;
var<workgroup> stage_q : array<f32, 512>;
var<workgroup> stage_k : array<f32, 512>;
var<workgroup> t_pstage : array<f32, 1024>;   // a redistributed fragment
var<workgroup> scratch : array<f32, 512>;   // tile rows x lanes along the folded axis

@compute @workgroup_size(16, 16, 1)
fn attention_f32(@builtin(workgroup_id)        wg  : vec3<u32>,
                @builtin(local_invocation_id) lid : vec3<u32>) {
  let tx = lid.x;
  let ty = lid.y;
  let tid = ty * 16u + tx;
  let base_m = wg.y * 32u;
  let base_d = wg.x * 16u;

  var mx : array<f32, 2>;
  mx[0] = -3.4028234663852886e38;
  mx[1] = -3.4028234663852886e38;
  var sm : array<f32, 2>;
  sm[0] = 0.0;
  sm[1] = 0.0;
  var acc : array<f32, 2>;
  acc[0] = 0.0;
  acc[1] = 0.0;

  for (var t_cb : u32 = 0u; t_cb < 768u; t_cb = t_cb + 32u) {
    let base_n = t_cb;
    var s : array<f32, 4>;
    s[0] = 0.0;
    s[1] = 0.0;
    s[2] = 0.0;
    s[3] = 0.0;
  for (var t_cb_d : u32 = 0u; t_cb_d < 64u; t_cb_d = t_cb_d + 16u) {
    for (var t_i : u32 = tid; t_i < 512u; t_i = t_i + 256u) {
      let t_r = t_i / 16u;
      let t_cc = t_i % 16u;
      let t_gr = base_m + t_r;
      let t_gc = t_cb_d + t_cc;
      let off0 = t_gr * 64u + t_gc;
      stage_q[t_i] = q[off0];
    }
    for (var t_i : u32 = tid; t_i < 512u; t_i = t_i + 256u) {
      let t_r = t_i / 32u;
      let t_cc = t_i % 32u;
      let t_gr = t_cb_d + t_r;
      let t_gc = base_n + t_cc;
      let off1 = t_gc * 64u + t_gr;
      stage_k[t_i] = k[off1];
    }
    workgroupBarrier();

    let t_base_q_0 = (ty * 2u + 0u) * 16u;
    let t_base_q_1 = (ty * 2u + 1u) * 16u;
    let t_base_k_0 = tx * 2u + 0u;
    let t_base_k_1 = tx * 2u + 1u;
    for (var t_s : u32 = 0u; t_s < 16u; t_s = t_s + 1u) {
      let t_lc = t_s;
      let t_ci = t_cb_d + t_lc;
        let v_q_0 = stage_q[t_base_q_0 + t_lc];
        let v_q_1 = stage_q[t_base_q_1 + t_lc];
        let v_k_0 = stage_k[t_lc * 32u + t_base_k_0];
        let v_k_1 = stage_k[t_lc * 32u + t_base_k_1];
        s[0] = s[0] + v_q_0 * v_k_0;
        s[1] = s[1] + v_q_0 * v_k_1;
        s[2] = s[2] + v_q_1 * v_k_0;
        s[3] = s[3] + v_q_1 * v_k_1;
    }
    workgroupBarrier();
  }

    {
      var t_p = -3.4028234663852886e38;
      t_p = max(t_p, s[0]);
      t_p = max(t_p, s[1]);
      scratch[(ty * 2u + 0u) * 16u + tx] = t_p;
    }
    {
      var t_p = -3.4028234663852886e38;
      t_p = max(t_p, s[2]);
      t_p = max(t_p, s[3]);
      scratch[(ty * 2u + 1u) * 16u + tx] = t_p;
    }
    workgroupBarrier();
    {
      var t_r = -3.4028234663852886e38;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = max(t_r, scratch[(ty * 2u + 0u) * 16u + t_j]);
      }
      mx[0] = max(mx[0], t_r);
    }
    {
      var t_r = -3.4028234663852886e38;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = max(t_r, scratch[(ty * 2u + 1u) * 16u + t_j]);
      }
      mx[1] = max(mx[1], t_r);
    }
    workgroupBarrier();
  }

  for (var t_cb : u32 = 0u; t_cb < 768u; t_cb = t_cb + 32u) {
    let base_n = t_cb;
    var s : array<f32, 4>;
    s[0] = 0.0;
    s[1] = 0.0;
    s[2] = 0.0;
    s[3] = 0.0;
  for (var t_cb_d : u32 = 0u; t_cb_d < 64u; t_cb_d = t_cb_d + 16u) {
    for (var t_i : u32 = tid; t_i < 512u; t_i = t_i + 256u) {
      let t_r = t_i / 16u;
      let t_cc = t_i % 16u;
      let t_gr = base_m + t_r;
      let t_gc = t_cb_d + t_cc;
      let off2 = t_gr * 64u + t_gc;
      stage_q[t_i] = q[off2];
    }
    for (var t_i : u32 = tid; t_i < 512u; t_i = t_i + 256u) {
      let t_r = t_i / 32u;
      let t_cc = t_i % 32u;
      let t_gr = t_cb_d + t_r;
      let t_gc = base_n + t_cc;
      let off3 = t_gc * 64u + t_gr;
      stage_k[t_i] = k[off3];
    }
    workgroupBarrier();

    let t_base_q_0 = (ty * 2u + 0u) * 16u;
    let t_base_q_1 = (ty * 2u + 1u) * 16u;
    let t_base_k_0 = tx * 2u + 0u;
    let t_base_k_1 = tx * 2u + 1u;
    for (var t_s : u32 = 0u; t_s < 16u; t_s = t_s + 1u) {
      let t_lc = t_s;
      let t_ci = t_cb_d + t_lc;
        let v_q_0 = stage_q[t_base_q_0 + t_lc];
        let v_q_1 = stage_q[t_base_q_1 + t_lc];
        let v_k_0 = stage_k[t_lc * 32u + t_base_k_0];
        let v_k_1 = stage_k[t_lc * 32u + t_base_k_1];
        s[0] = s[0] + v_q_0 * v_k_0;
        s[1] = s[1] + v_q_0 * v_k_1;
        s[2] = s[2] + v_q_1 * v_k_0;
        s[3] = s[3] + v_q_1 * v_k_1;
    }
    workgroupBarrier();
  }

    {
      var t_p = 0.0;
      t_p = t_p + exp((s[0] - mx[0]));
      t_p = t_p + exp((s[1] - mx[0]));
      scratch[(ty * 2u + 0u) * 16u + tx] = t_p;
    }
    {
      var t_p = 0.0;
      t_p = t_p + exp((s[2] - mx[1]));
      t_p = t_p + exp((s[3] - mx[1]));
      scratch[(ty * 2u + 1u) * 16u + tx] = t_p;
    }
    workgroupBarrier();
    {
      var t_r = 0.0;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = t_r + scratch[(ty * 2u + 0u) * 16u + t_j];
      }
      sm[0] = sm[0] + t_r;
    }
    {
      var t_r = 0.0;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = t_r + scratch[(ty * 2u + 1u) * 16u + t_j];
      }
      sm[1] = sm[1] + t_r;
    }
    workgroupBarrier();
  }

  for (var t_cb : u32 = 0u; t_cb < 768u; t_cb = t_cb + 32u) {
    let base_n = t_cb;
    var s : array<f32, 4>;
    s[0] = 0.0;
    s[1] = 0.0;
    s[2] = 0.0;
    s[3] = 0.0;
  for (var t_cb_d : u32 = 0u; t_cb_d < 64u; t_cb_d = t_cb_d + 16u) {
    for (var t_i : u32 = tid; t_i < 512u; t_i = t_i + 256u) {
      let t_r = t_i / 16u;
      let t_cc = t_i % 16u;
      let t_gr = base_m + t_r;
      let t_gc = t_cb_d + t_cc;
      let off4 = t_gr * 64u + t_gc;
      stage_q[t_i] = q[off4];
    }
    for (var t_i : u32 = tid; t_i < 512u; t_i = t_i + 256u) {
      let t_r = t_i / 32u;
      let t_cc = t_i % 32u;
      let t_gr = t_cb_d + t_r;
      let t_gc = base_n + t_cc;
      let off5 = t_gc * 64u + t_gr;
      stage_k[t_i] = k[off5];
    }
    workgroupBarrier();

    let t_base_q_0 = (ty * 2u + 0u) * 16u;
    let t_base_q_1 = (ty * 2u + 1u) * 16u;
    let t_base_k_0 = tx * 2u + 0u;
    let t_base_k_1 = tx * 2u + 1u;
    for (var t_s : u32 = 0u; t_s < 16u; t_s = t_s + 1u) {
      let t_lc = t_s;
      let t_ci = t_cb_d + t_lc;
        let v_q_0 = stage_q[t_base_q_0 + t_lc];
        let v_q_1 = stage_q[t_base_q_1 + t_lc];
        let v_k_0 = stage_k[t_lc * 32u + t_base_k_0];
        let v_k_1 = stage_k[t_lc * 32u + t_base_k_1];
        s[0] = s[0] + v_q_0 * v_k_0;
        s[1] = s[1] + v_q_0 * v_k_1;
        s[2] = s[2] + v_q_1 * v_k_0;
        s[3] = s[3] + v_q_1 * v_k_1;
    }
    workgroupBarrier();
  }

    t_pstage[(ty * 2u + 0u) * 32u + (tx * 2u + 0u)] = (exp((s[0] - mx[0])) / sm[0]);
    t_pstage[(ty * 2u + 0u) * 32u + (tx * 2u + 1u)] = (exp((s[1] - mx[0])) / sm[0]);
    t_pstage[(ty * 2u + 1u) * 32u + (tx * 2u + 0u)] = (exp((s[2] - mx[1])) / sm[1]);
    t_pstage[(ty * 2u + 1u) * 32u + (tx * 2u + 1u)] = (exp((s[3] - mx[1])) / sm[1]);
    for (var t_i : u32 = tid; t_i < 512u; t_i = t_i + 256u) {
      let t_r = t_i / 16u;
      let t_cc = t_i % 16u;
      let t_gr = t_cb + t_r;
      let t_gc = base_d + t_cc;
      let off6 = t_gr * 64u + t_gc;
      stage_v[t_i] = v[off6];
    }
    workgroupBarrier();
    for (var t_ci : u32 = 0u; t_ci < 32u; t_ci = t_ci + 1u) {
      acc[0] = acc[0] + t_pstage[(ty * 2u + 0u) * 32u + t_ci] * stage_v[t_ci * 16u + (tx * 1u + 0u)];
      acc[1] = acc[1] + t_pstage[(ty * 2u + 1u) * 32u + t_ci] * stage_v[t_ci * 16u + (tx * 1u + 0u)];
    }
    workgroupBarrier();
  }

  o[(base_m + ty * 2u + 0u) * 64u + (base_d + tx * 1u + 0u)] = acc[0];
  o[(base_m + ty * 2u + 1u) * 64u + (base_d + tx * 1u + 0u)] = acc[1];
}
