// Generated by tessera from a TypeScript kernel. Do not edit.
//
//   layernorm_f32   accumulate (m)   contract n
//   lanes m->y(4)  n->x   fragment 4   4 sequential steps
//   staged: nothing — no operand is reused   workgroup 4096 B
//   masked: x:n y:n   pad x=zero

@group(0) @binding(0) var<storage, read> x : array<f32>;
@group(0) @binding(1) var<storage, read_write> y : array<f32>;

var<workgroup> scratch : array<f32, 1024>;   // fragment x lanes

@compute @workgroup_size(16, 16, 1)
fn layernorm_f32(@builtin(workgroup_id)        wg  : vec3<u32>,
                @builtin(local_invocation_id) lid : vec3<u32>) {
  let tx = lid.x;
  let ty = lid.y;
  let tid = ty * 16u + tx;
  let base_m = wg.x * 64u;

  var s : array<f32, 4>;
  s[0] = 0.0;
  s[1] = 0.0;
  s[2] = 0.0;
  s[3] = 0.0;
  var q : array<f32, 4>;
  q[0] = 0.0;
  q[1] = 0.0;
  q[2] = 0.0;
  q[3] = 0.0;

  for (var t_cb : u32 = 0u; t_cb < 750u; t_cb = t_cb + 64u) {
    for (var t_s : u32 = 0u; t_s < 4u; t_s = t_s + 1u) {
      let t_lc = tx * 4u + t_s;
      let t_ci = t_cb + t_lc;
        let off0 = (base_m + ty * 4u + 0u) * 750u + (t_ci);
        let v_x_0 = select(0.0, x[min(off0, 767999u)], (t_ci) < 750u);
        let off1 = (base_m + ty * 4u + 1u) * 750u + (t_ci);
        let v_x_1 = select(0.0, x[min(off1, 767999u)], (t_ci) < 750u);
        let off2 = (base_m + ty * 4u + 2u) * 750u + (t_ci);
        let v_x_2 = select(0.0, x[min(off2, 767999u)], (t_ci) < 750u);
        let off3 = (base_m + ty * 4u + 3u) * 750u + (t_ci);
        let v_x_3 = select(0.0, x[min(off3, 767999u)], (t_ci) < 750u);
        s[0] = s[0] + v_x_0;
        q[0] = q[0] + (v_x_0 * v_x_0);
        s[1] = s[1] + v_x_1;
        q[1] = q[1] + (v_x_1 * v_x_1);
        s[2] = s[2] + v_x_2;
        q[2] = q[2] + (v_x_2 * v_x_2);
        s[3] = s[3] + v_x_3;
        q[3] = q[3] + (v_x_3 * v_x_3);
    }
  }

  scratch[(ty * 4u + 0u) * 16u + tx] = s[0];
  scratch[(ty * 4u + 1u) * 16u + tx] = s[1];
  scratch[(ty * 4u + 2u) * 16u + tx] = s[2];
  scratch[(ty * 4u + 3u) * 16u + tx] = s[3];
  workgroupBarrier();
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 0u) * 16u + t_j];
    }
    s[0] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 1u) * 16u + t_j];
    }
    s[1] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 2u) * 16u + t_j];
    }
    s[2] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 3u) * 16u + t_j];
    }
    s[3] = t_r;
  }
  workgroupBarrier();
  scratch[(ty * 4u + 0u) * 16u + tx] = q[0];
  scratch[(ty * 4u + 1u) * 16u + tx] = q[1];
  scratch[(ty * 4u + 2u) * 16u + tx] = q[2];
  scratch[(ty * 4u + 3u) * 16u + tx] = q[3];
  workgroupBarrier();
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 0u) * 16u + t_j];
    }
    q[0] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 1u) * 16u + t_j];
    }
    q[1] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 2u) * 16u + t_j];
    }
    q[2] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 3u) * 16u + t_j];
    }
    q[3] = t_r;
  }
  workgroupBarrier();

  var mu : array<f32, 4>;
  mu[0] = (s[0] / 750.0);
  mu[1] = (s[1] / 750.0);
  mu[2] = (s[2] / 750.0);
  mu[3] = (s[3] / 750.0);

  var inv : array<f32, 4>;
  inv[0] = inverseSqrt((q[0] / 750.0) - mu[0] * mu[0] + 0.00001);
  inv[1] = inverseSqrt((q[1] / 750.0) - mu[1] * mu[1] + 0.00001);
  inv[2] = inverseSqrt((q[2] / 750.0) - mu[2] * mu[2] + 0.00001);
  inv[3] = inverseSqrt((q[3] / 750.0) - mu[3] * mu[3] + 0.00001);

  for (var t_cb : u32 = 0u; t_cb < 750u; t_cb = t_cb + 64u) {
    for (var t_s : u32 = 0u; t_s < 4u; t_s = t_s + 1u) {
      let t_lc = tx * 4u + t_s;
      let t_ci = t_cb + t_lc;
        let off4 = (base_m + ty * 4u + 0u) * 750u + (t_ci);
        let v_x_0 = select(0.0, x[min(off4, 767999u)], (t_ci) < 750u);
        let off5 = (base_m + ty * 4u + 1u) * 750u + (t_ci);
        let v_x_1 = select(0.0, x[min(off5, 767999u)], (t_ci) < 750u);
        let off6 = (base_m + ty * 4u + 2u) * 750u + (t_ci);
        let v_x_2 = select(0.0, x[min(off6, 767999u)], (t_ci) < 750u);
        let off7 = (base_m + ty * 4u + 3u) * 750u + (t_ci);
        let v_x_3 = select(0.0, x[min(off7, 767999u)], (t_ci) < 750u);
        if ((t_ci) < 750u) {
          y[(base_m + ty * 4u + 0u) * 750u + (t_ci)] = ((v_x_0 - mu[0]) * inv[0]);
        }
        if ((t_ci) < 750u) {
          y[(base_m + ty * 4u + 1u) * 750u + (t_ci)] = ((v_x_1 - mu[1]) * inv[1]);
        }
        if ((t_ci) < 750u) {
          y[(base_m + ty * 4u + 2u) * 750u + (t_ci)] = ((v_x_2 - mu[2]) * inv[2]);
        }
        if ((t_ci) < 750u) {
          y[(base_m + ty * 4u + 3u) * 750u + (t_ci)] = ((v_x_3 - mu[3]) * inv[3]);
        }
    }
  }
}
