// Generated by tessera from a TypeScript kernel. Do not edit.
//
//   layernorm_f32: m=1024 x n=750
//   schedule rowwise   workgroup 16x16x1   fragment 4x4
//   masked: x:n y:n   pad zero (0.0)

@group(0) @binding(0) var<storage, read> x : array<f32>;
@group(0) @binding(1) var<storage, read_write> y : array<f32>;

var<workgroup> scratch : array<f32, 1024>;   // rows x lanes

@compute @workgroup_size(16, 16, 1)
fn layernorm_f32(@builtin(workgroup_id)        wg  : vec3<u32>,
                @builtin(local_invocation_id) lid : vec3<u32>) {
  let blockRow = wg.x;
  let tx  = lid.x;
  let ty  = lid.y;
  let rowBase = blockRow * 64u;

  var s : array<f32, 4>;
  s[0] = 0.0;
  s[1] = 0.0;
  s[2] = 0.0;
  s[3] = 0.0;
  var q : array<f32, 4>;
  q[0] = 0.0;
  q[1] = 0.0;
  q[2] = 0.0;
  q[3] = 0.0;

  for (var nn : u32 = 0u; nn < 750u; nn = nn + 64u) {
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[0] = s[0] + v;
      q[0] = q[0] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[0] = s[0] + v;
      q[0] = q[0] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[0] = s[0] + v;
      q[0] = q[0] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[0] = s[0] + v;
      q[0] = q[0] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[1] = s[1] + v;
      q[1] = q[1] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[1] = s[1] + v;
      q[1] = q[1] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[1] = s[1] + v;
      q[1] = q[1] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[1] = s[1] + v;
      q[1] = q[1] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[2] = s[2] + v;
      q[2] = q[2] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[2] = s[2] + v;
      q[2] = q[2] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[2] = s[2] + v;
      q[2] = q[2] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[2] = s[2] + v;
      q[2] = q[2] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[3] = s[3] + v;
      q[3] = q[3] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[3] = s[3] + v;
      q[3] = q[3] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[3] = s[3] + v;
      q[3] = q[3] + (v * v);
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      s[3] = s[3] + v;
      q[3] = q[3] + (v * v);
    }
  }
  scratch[(ty * 4u + 0u) * 16u + tx] = s[0];
  scratch[(ty * 4u + 1u) * 16u + tx] = s[1];
  scratch[(ty * 4u + 2u) * 16u + tx] = s[2];
  scratch[(ty * 4u + 3u) * 16u + tx] = s[3];
  workgroupBarrier();
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 0u) * 16u + j];
    }
    s[0] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 1u) * 16u + j];
    }
    s[1] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 2u) * 16u + j];
    }
    s[2] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 3u) * 16u + j];
    }
    s[3] = r;
  }
  workgroupBarrier();
  scratch[(ty * 4u + 0u) * 16u + tx] = q[0];
  scratch[(ty * 4u + 1u) * 16u + tx] = q[1];
  scratch[(ty * 4u + 2u) * 16u + tx] = q[2];
  scratch[(ty * 4u + 3u) * 16u + tx] = q[3];
  workgroupBarrier();
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 0u) * 16u + j];
    }
    q[0] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 1u) * 16u + j];
    }
    q[1] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 2u) * 16u + j];
    }
    q[2] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 3u) * 16u + j];
    }
    q[3] = r;
  }
  workgroupBarrier();

  var mu : array<f32, 4>;
  mu[0] = (s[0] / 750.0);
  mu[1] = (s[1] / 750.0);
  mu[2] = (s[2] / 750.0);
  mu[3] = (s[3] / 750.0);

  var inv : array<f32, 4>;
  inv[0] = inverseSqrt((q[0] / 750.0) - mu[0] * mu[0] + 0.00001);
  inv[1] = inverseSqrt((q[1] / 750.0) - mu[1] * mu[1] + 0.00001);
  inv[2] = inverseSqrt((q[2] / 750.0) - mu[2] * mu[2] + 0.00001);
  inv[3] = inverseSqrt((q[3] / 750.0) - mu[3] * mu[3] + 0.00001);

  for (var nn : u32 = 0u; nn < 750u; nn = nn + 64u) {
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[0]) * inv[0]);
      }
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[0]) * inv[0]);
      }
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[0]) * inv[0]);
      }
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[0]) * inv[0]);
      }
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[1]) * inv[1]);
      }
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[1]) * inv[1]);
      }
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[1]) * inv[1]);
      }
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[1]) * inv[1]);
      }
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[2]) * inv[2]);
      }
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[2]) * inv[2]);
      }
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[2]) * inv[2]);
      }
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[2]) * inv[2]);
      }
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[3]) * inv[3]);
      }
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[3]) * inv[3]);
      }
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[3]) * inv[3]);
      }
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(0.0, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = ((v - mu[3]) * inv[3]);
      }
    }
  }

}
