// Generated by tessera from a TypeScript kernel. Do not edit.
//
//   matmul_relu_ragged: m=1000 x n=750 x k=500
//   schedule matmul   workgroup 16x16x1   fragment 4x4
//   masked: a:m a:k b:k b:n c:m c:n   pad zero (0.0)

@group(0) @binding(0) var<storage, read> a : array<f32>;
@group(0) @binding(1) var<storage, read> b : array<f32>;
@group(0) @binding(2) var<storage, read_write> c : array<f32>;

var<workgroup> As : array<f32, 1024>;
var<workgroup> Bs : array<f32, 1024>;

@compute @workgroup_size(16, 16, 1)
fn matmul_relu_ragged(@builtin(workgroup_id)        wg  : vec3<u32>,
                     @builtin(local_invocation_id) lid : vec3<u32>) {
  let blockRow = wg.y;
  let blockCol = wg.x;
  let tx  = lid.x;
  let ty  = lid.y;
  let tid = ty * 16u + tx;
  let rowBase = blockRow * 64u;
  let colBase = blockCol * 64u;

  var acc : array<f32, 16>;

  for (var kk : u32 = 0u; kk < 500u; kk = kk + 16u) {
    for (var i : u32 = tid; i < 1024u; i = i + 256u) {
      let r  = i / 16u;
      let cc = i % 16u;
      let gr = rowBase + r;
      let gc = kk + cc;
      let off = gr * 500u + gc;
      As[i] = select(0.0, a[min(off, 499999u)], gr < 1000u && gc < 500u);
    }
    for (var i : u32 = tid; i < 1024u; i = i + 256u) {
      let r  = i / 64u;
      let cc = i % 64u;
      let gr = kk + r;
      let gc = colBase + cc;
      let off = gr * 750u + gc;
      Bs[i] = select(0.0, b[min(off, 374999u)], gr < 500u && gc < 750u);
    }
    workgroupBarrier();

    for (var k : u32 = 0u; k < 16u; k = k + 1u) {
      let af0 = As[(ty * 4u + 0u) * 16u + k];
      let af1 = As[(ty * 4u + 1u) * 16u + k];
      let af2 = As[(ty * 4u + 2u) * 16u + k];
      let af3 = As[(ty * 4u + 3u) * 16u + k];
      let bf0 = Bs[k * 64u + (tx * 4u + 0u)];
      let bf1 = Bs[k * 64u + (tx * 4u + 1u)];
      let bf2 = Bs[k * 64u + (tx * 4u + 2u)];
      let bf3 = Bs[k * 64u + (tx * 4u + 3u)];
      acc[0] = acc[0] + af0 * bf0;
      acc[1] = acc[1] + af0 * bf1;
      acc[2] = acc[2] + af0 * bf2;
      acc[3] = acc[3] + af0 * bf3;
      acc[4] = acc[4] + af1 * bf0;
      acc[5] = acc[5] + af1 * bf1;
      acc[6] = acc[6] + af1 * bf2;
      acc[7] = acc[7] + af1 * bf3;
      acc[8] = acc[8] + af2 * bf0;
      acc[9] = acc[9] + af2 * bf1;
      acc[10] = acc[10] + af2 * bf2;
      acc[11] = acc[11] + af2 * bf3;
      acc[12] = acc[12] + af3 * bf0;
      acc[13] = acc[13] + af3 * bf1;
      acc[14] = acc[14] + af3 * bf2;
      acc[15] = acc[15] + af3 * bf3;
    }

    workgroupBarrier();
  }

  let row0 = rowBase + ty * 4u + 0u;
  let col0 = colBase + tx * 4u + 0u;
  if (row0 < 1000u && col0 < 750u) {
    c[row0 * 750u + col0] = select(0.0, acc[0], acc[0] > 0.0);
  }
  let col1 = colBase + tx * 4u + 1u;
  if (row0 < 1000u && col1 < 750u) {
    c[row0 * 750u + col1] = select(0.0, acc[1], acc[1] > 0.0);
  }
  let col2 = colBase + tx * 4u + 2u;
  if (row0 < 1000u && col2 < 750u) {
    c[row0 * 750u + col2] = select(0.0, acc[2], acc[2] > 0.0);
  }
  let col3 = colBase + tx * 4u + 3u;
  if (row0 < 1000u && col3 < 750u) {
    c[row0 * 750u + col3] = select(0.0, acc[3], acc[3] > 0.0);
  }
  let row1 = rowBase + ty * 4u + 1u;
  let col4 = colBase + tx * 4u + 0u;
  if (row1 < 1000u && col4 < 750u) {
    c[row1 * 750u + col4] = select(0.0, acc[4], acc[4] > 0.0);
  }
  let col5 = colBase + tx * 4u + 1u;
  if (row1 < 1000u && col5 < 750u) {
    c[row1 * 750u + col5] = select(0.0, acc[5], acc[5] > 0.0);
  }
  let col6 = colBase + tx * 4u + 2u;
  if (row1 < 1000u && col6 < 750u) {
    c[row1 * 750u + col6] = select(0.0, acc[6], acc[6] > 0.0);
  }
  let col7 = colBase + tx * 4u + 3u;
  if (row1 < 1000u && col7 < 750u) {
    c[row1 * 750u + col7] = select(0.0, acc[7], acc[7] > 0.0);
  }
  let row2 = rowBase + ty * 4u + 2u;
  let col8 = colBase + tx * 4u + 0u;
  if (row2 < 1000u && col8 < 750u) {
    c[row2 * 750u + col8] = select(0.0, acc[8], acc[8] > 0.0);
  }
  let col9 = colBase + tx * 4u + 1u;
  if (row2 < 1000u && col9 < 750u) {
    c[row2 * 750u + col9] = select(0.0, acc[9], acc[9] > 0.0);
  }
  let col10 = colBase + tx * 4u + 2u;
  if (row2 < 1000u && col10 < 750u) {
    c[row2 * 750u + col10] = select(0.0, acc[10], acc[10] > 0.0);
  }
  let col11 = colBase + tx * 4u + 3u;
  if (row2 < 1000u && col11 < 750u) {
    c[row2 * 750u + col11] = select(0.0, acc[11], acc[11] > 0.0);
  }
  let row3 = rowBase + ty * 4u + 3u;
  let col12 = colBase + tx * 4u + 0u;
  if (row3 < 1000u && col12 < 750u) {
    c[row3 * 750u + col12] = select(0.0, acc[12], acc[12] > 0.0);
  }
  let col13 = colBase + tx * 4u + 1u;
  if (row3 < 1000u && col13 < 750u) {
    c[row3 * 750u + col13] = select(0.0, acc[13], acc[13] > 0.0);
  }
  let col14 = colBase + tx * 4u + 2u;
  if (row3 < 1000u && col14 < 750u) {
    c[row3 * 750u + col14] = select(0.0, acc[14], acc[14] > 0.0);
  }
  let col15 = colBase + tx * 4u + 3u;
  if (row3 < 1000u && col15 < 750u) {
    c[row3 * 750u + col15] = select(0.0, acc[15], acc[15] > 0.0);
  }
}
