// Generated by tessera from a TypeScript kernel. Do not edit.
//
//   matmul_relu_ragged   accumulate (m, n)   contract k
//   lanes m->y(4) n->x(4)   fragment 16   16 sequential steps
//   staged: a, b   workgroup 8192 B
//   masked: a:m a:k b:k b:n c:m c:n   pad zero (0.0)

@group(0) @binding(0) var<storage, read> a : array<f32>;
@group(0) @binding(1) var<storage, read> b : array<f32>;
@group(0) @binding(2) var<storage, read_write> c : array<f32>;

var<workgroup> stage_a : array<f32, 1024>;
var<workgroup> stage_b : array<f32, 1024>;

@compute @workgroup_size(16, 16, 1)
fn matmul_relu_ragged(@builtin(workgroup_id)        wg  : vec3<u32>,
                     @builtin(local_invocation_id) lid : vec3<u32>) {
  let tx = lid.x;
  let ty = lid.y;
  let tid = ty * 16u + tx;
  let base_m = wg.y * 64u;
  let base_n = wg.x * 64u;

  var acc : array<f32, 16>;
  acc[0] = 0.0;
  acc[1] = 0.0;
  acc[2] = 0.0;
  acc[3] = 0.0;
  acc[4] = 0.0;
  acc[5] = 0.0;
  acc[6] = 0.0;
  acc[7] = 0.0;
  acc[8] = 0.0;
  acc[9] = 0.0;
  acc[10] = 0.0;
  acc[11] = 0.0;
  acc[12] = 0.0;
  acc[13] = 0.0;
  acc[14] = 0.0;
  acc[15] = 0.0;

  for (var t_cb : u32 = 0u; t_cb < 500u; t_cb = t_cb + 16u) {
    for (var t_i : u32 = tid; t_i < 1024u; t_i = t_i + 256u) {
      let t_r = t_i / 16u;
      let t_cc = t_i % 16u;
      let t_gr = base_m + t_r;
      let t_gc = t_cb + t_cc;
      let off0 = t_gr * 500u + t_gc;
      stage_a[t_i] = select(0.0, a[min(off0, 499999u)], t_gr < 1000u && t_gc < 500u);
    }
    for (var t_i : u32 = tid; t_i < 1024u; t_i = t_i + 256u) {
      let t_r = t_i / 64u;
      let t_cc = t_i % 64u;
      let t_gr = t_cb + t_r;
      let t_gc = base_n + t_cc;
      let off1 = t_gr * 750u + t_gc;
      stage_b[t_i] = select(0.0, b[min(off1, 374999u)], t_gr < 500u && t_gc < 750u);
    }
    workgroupBarrier();

    for (var t_s : u32 = 0u; t_s < 16u; t_s = t_s + 1u) {
      let t_ci = t_cb + t_s;
        let v_a_0 = stage_a[(ty * 4u + 0u) * 16u + (t_ci - t_cb)];
        let v_a_1 = stage_a[(ty * 4u + 1u) * 16u + (t_ci - t_cb)];
        let v_a_2 = stage_a[(ty * 4u + 2u) * 16u + (t_ci - t_cb)];
        let v_a_3 = stage_a[(ty * 4u + 3u) * 16u + (t_ci - t_cb)];
        let v_b_0 = stage_b[(t_ci - t_cb) * 64u + (tx * 4u + 0u)];
        let v_b_1 = stage_b[(t_ci - t_cb) * 64u + (tx * 4u + 1u)];
        let v_b_2 = stage_b[(t_ci - t_cb) * 64u + (tx * 4u + 2u)];
        let v_b_3 = stage_b[(t_ci - t_cb) * 64u + (tx * 4u + 3u)];
        acc[0] = acc[0] + v_a_0 * v_b_0;
        acc[1] = acc[1] + v_a_0 * v_b_1;
        acc[2] = acc[2] + v_a_0 * v_b_2;
        acc[3] = acc[3] + v_a_0 * v_b_3;
        acc[4] = acc[4] + v_a_1 * v_b_0;
        acc[5] = acc[5] + v_a_1 * v_b_1;
        acc[6] = acc[6] + v_a_1 * v_b_2;
        acc[7] = acc[7] + v_a_1 * v_b_3;
        acc[8] = acc[8] + v_a_2 * v_b_0;
        acc[9] = acc[9] + v_a_2 * v_b_1;
        acc[10] = acc[10] + v_a_2 * v_b_2;
        acc[11] = acc[11] + v_a_2 * v_b_3;
        acc[12] = acc[12] + v_a_3 * v_b_0;
        acc[13] = acc[13] + v_a_3 * v_b_1;
        acc[14] = acc[14] + v_a_3 * v_b_2;
        acc[15] = acc[15] + v_a_3 * v_b_3;
    }
    workgroupBarrier();
  }

  if ((base_m + ty * 4u + 0u) < 1000u && (base_n + tx * 4u + 0u) < 750u) {
    c[(base_m + ty * 4u + 0u) * 750u + (base_n + tx * 4u + 0u)] = select(0.0, acc[0], acc[0] > 0.0);
  }
  if ((base_m + ty * 4u + 0u) < 1000u && (base_n + tx * 4u + 1u) < 750u) {
    c[(base_m + ty * 4u + 0u) * 750u + (base_n + tx * 4u + 1u)] = select(0.0, acc[1], acc[1] > 0.0);
  }
  if ((base_m + ty * 4u + 0u) < 1000u && (base_n + tx * 4u + 2u) < 750u) {
    c[(base_m + ty * 4u + 0u) * 750u + (base_n + tx * 4u + 2u)] = select(0.0, acc[2], acc[2] > 0.0);
  }
  if ((base_m + ty * 4u + 0u) < 1000u && (base_n + tx * 4u + 3u) < 750u) {
    c[(base_m + ty * 4u + 0u) * 750u + (base_n + tx * 4u + 3u)] = select(0.0, acc[3], acc[3] > 0.0);
  }
  if ((base_m + ty * 4u + 1u) < 1000u && (base_n + tx * 4u + 0u) < 750u) {
    c[(base_m + ty * 4u + 1u) * 750u + (base_n + tx * 4u + 0u)] = select(0.0, acc[4], acc[4] > 0.0);
  }
  if ((base_m + ty * 4u + 1u) < 1000u && (base_n + tx * 4u + 1u) < 750u) {
    c[(base_m + ty * 4u + 1u) * 750u + (base_n + tx * 4u + 1u)] = select(0.0, acc[5], acc[5] > 0.0);
  }
  if ((base_m + ty * 4u + 1u) < 1000u && (base_n + tx * 4u + 2u) < 750u) {
    c[(base_m + ty * 4u + 1u) * 750u + (base_n + tx * 4u + 2u)] = select(0.0, acc[6], acc[6] > 0.0);
  }
  if ((base_m + ty * 4u + 1u) < 1000u && (base_n + tx * 4u + 3u) < 750u) {
    c[(base_m + ty * 4u + 1u) * 750u + (base_n + tx * 4u + 3u)] = select(0.0, acc[7], acc[7] > 0.0);
  }
  if ((base_m + ty * 4u + 2u) < 1000u && (base_n + tx * 4u + 0u) < 750u) {
    c[(base_m + ty * 4u + 2u) * 750u + (base_n + tx * 4u + 0u)] = select(0.0, acc[8], acc[8] > 0.0);
  }
  if ((base_m + ty * 4u + 2u) < 1000u && (base_n + tx * 4u + 1u) < 750u) {
    c[(base_m + ty * 4u + 2u) * 750u + (base_n + tx * 4u + 1u)] = select(0.0, acc[9], acc[9] > 0.0);
  }
  if ((base_m + ty * 4u + 2u) < 1000u && (base_n + tx * 4u + 2u) < 750u) {
    c[(base_m + ty * 4u + 2u) * 750u + (base_n + tx * 4u + 2u)] = select(0.0, acc[10], acc[10] > 0.0);
  }
  if ((base_m + ty * 4u + 2u) < 1000u && (base_n + tx * 4u + 3u) < 750u) {
    c[(base_m + ty * 4u + 2u) * 750u + (base_n + tx * 4u + 3u)] = select(0.0, acc[11], acc[11] > 0.0);
  }
  if ((base_m + ty * 4u + 3u) < 1000u && (base_n + tx * 4u + 0u) < 750u) {
    c[(base_m + ty * 4u + 3u) * 750u + (base_n + tx * 4u + 0u)] = select(0.0, acc[12], acc[12] > 0.0);
  }
  if ((base_m + ty * 4u + 3u) < 1000u && (base_n + tx * 4u + 1u) < 750u) {
    c[(base_m + ty * 4u + 3u) * 750u + (base_n + tx * 4u + 1u)] = select(0.0, acc[13], acc[13] > 0.0);
  }
  if ((base_m + ty * 4u + 3u) < 1000u && (base_n + tx * 4u + 2u) < 750u) {
    c[(base_m + ty * 4u + 3u) * 750u + (base_n + tx * 4u + 2u)] = select(0.0, acc[14], acc[14] > 0.0);
  }
  if ((base_m + ty * 4u + 3u) < 1000u && (base_n + tx * 4u + 3u) < 750u) {
    c[(base_m + ty * 4u + 3u) * 750u + (base_n + tx * 4u + 3u)] = select(0.0, acc[15], acc[15] > 0.0);
  }
}
