// Generated by tessera from a TypeScript kernel. Do not edit.
//
//   nested_softmax_f32   accumulate (m)   contract n
//   lanes m->y(4)  n->x   fragment 4   4 sequential steps
//   staged: nothing — no operand is reused   workgroup 4096 B
//   no masks: every axis divides its block

@group(0) @binding(0) var<storage, read> a : array<f32>;
@group(0) @binding(1) var<storage, read> b : array<f32>;
@group(0) @binding(2) var<storage, read_write> y : array<f32>;

var<workgroup> stage_a : array<f32, 1024>;
var<workgroup> stage_b : array<f32, 1024>;
var<workgroup> scratch : array<f32, 1024>;   // tile rows x lanes along the folded axis

@compute @workgroup_size(16, 16, 1)
fn nested_softmax_f32(@builtin(workgroup_id)        wg  : vec3<u32>,
                     @builtin(local_invocation_id) lid : vec3<u32>) {
  let tx = lid.x;
  let ty = lid.y;
  let tid = ty * 16u + tx;
  let base_m = wg.x * 64u;

  var mx : array<f32, 4>;
  mx[0] = -3.4028234663852886e38;
  mx[1] = -3.4028234663852886e38;
  mx[2] = -3.4028234663852886e38;
  mx[3] = -3.4028234663852886e38;
  var sm : array<f32, 4>;
  sm[0] = 0.0;
  sm[1] = 0.0;
  sm[2] = 0.0;
  sm[3] = 0.0;

  for (var t_cb : u32 = 0u; t_cb < 768u; t_cb = t_cb + 64u) {
    let base_n = t_cb;
    var s : array<f32, 16>;
    s[0] = 0.0;
    s[1] = 0.0;
    s[2] = 0.0;
    s[3] = 0.0;
    s[4] = 0.0;
    s[5] = 0.0;
    s[6] = 0.0;
    s[7] = 0.0;
    s[8] = 0.0;
    s[9] = 0.0;
    s[10] = 0.0;
    s[11] = 0.0;
    s[12] = 0.0;
    s[13] = 0.0;
    s[14] = 0.0;
    s[15] = 0.0;
  for (var t_cb_k : u32 = 0u; t_cb_k < 512u; t_cb_k = t_cb_k + 16u) {
    for (var t_i : u32 = tid; t_i < 1024u; t_i = t_i + 256u) {
      let t_r = t_i / 16u;
      let t_cc = t_i % 16u;
      let t_gr = base_m + t_r;
      let t_gc = t_cb_k + t_cc;
      let off0 = t_gr * 512u + t_gc;
      stage_a[t_i] = a[off0];
    }
    for (var t_i : u32 = tid; t_i < 1024u; t_i = t_i + 256u) {
      let t_r = t_i / 64u;
      let t_cc = t_i % 64u;
      let t_gr = t_cb_k + t_r;
      let t_gc = base_n + t_cc;
      let off1 = t_gr * 768u + t_gc;
      stage_b[t_i] = b[off1];
    }
    workgroupBarrier();

    let t_base_a_0 = (ty * 4u + 0u) * 16u;
    let t_base_a_1 = (ty * 4u + 1u) * 16u;
    let t_base_a_2 = (ty * 4u + 2u) * 16u;
    let t_base_a_3 = (ty * 4u + 3u) * 16u;
    let t_base_b_0 = tx * 4u + 0u;
    let t_base_b_1 = tx * 4u + 1u;
    let t_base_b_2 = tx * 4u + 2u;
    let t_base_b_3 = tx * 4u + 3u;
    for (var t_s : u32 = 0u; t_s < 16u; t_s = t_s + 1u) {
      let t_lc = t_s;
      let t_ci = t_cb_k + t_lc;
        let v_a_0 = stage_a[t_base_a_0 + t_lc];
        let v_a_1 = stage_a[t_base_a_1 + t_lc];
        let v_a_2 = stage_a[t_base_a_2 + t_lc];
        let v_a_3 = stage_a[t_base_a_3 + t_lc];
        let v_b_0 = stage_b[t_lc * 64u + t_base_b_0];
        let v_b_1 = stage_b[t_lc * 64u + t_base_b_1];
        let v_b_2 = stage_b[t_lc * 64u + t_base_b_2];
        let v_b_3 = stage_b[t_lc * 64u + t_base_b_3];
        s[0] = s[0] + v_a_0 * v_b_0;
        s[1] = s[1] + v_a_0 * v_b_1;
        s[2] = s[2] + v_a_0 * v_b_2;
        s[3] = s[3] + v_a_0 * v_b_3;
        s[4] = s[4] + v_a_1 * v_b_0;
        s[5] = s[5] + v_a_1 * v_b_1;
        s[6] = s[6] + v_a_1 * v_b_2;
        s[7] = s[7] + v_a_1 * v_b_3;
        s[8] = s[8] + v_a_2 * v_b_0;
        s[9] = s[9] + v_a_2 * v_b_1;
        s[10] = s[10] + v_a_2 * v_b_2;
        s[11] = s[11] + v_a_2 * v_b_3;
        s[12] = s[12] + v_a_3 * v_b_0;
        s[13] = s[13] + v_a_3 * v_b_1;
        s[14] = s[14] + v_a_3 * v_b_2;
        s[15] = s[15] + v_a_3 * v_b_3;
    }
    workgroupBarrier();
  }

    {
      var t_p = -3.4028234663852886e38;
      t_p = max(t_p, s[0]);
      t_p = max(t_p, s[1]);
      t_p = max(t_p, s[2]);
      t_p = max(t_p, s[3]);
      scratch[(ty * 4u + 0u) * 16u + tx] = t_p;
    }
    {
      var t_p = -3.4028234663852886e38;
      t_p = max(t_p, s[4]);
      t_p = max(t_p, s[5]);
      t_p = max(t_p, s[6]);
      t_p = max(t_p, s[7]);
      scratch[(ty * 4u + 1u) * 16u + tx] = t_p;
    }
    {
      var t_p = -3.4028234663852886e38;
      t_p = max(t_p, s[8]);
      t_p = max(t_p, s[9]);
      t_p = max(t_p, s[10]);
      t_p = max(t_p, s[11]);
      scratch[(ty * 4u + 2u) * 16u + tx] = t_p;
    }
    {
      var t_p = -3.4028234663852886e38;
      t_p = max(t_p, s[12]);
      t_p = max(t_p, s[13]);
      t_p = max(t_p, s[14]);
      t_p = max(t_p, s[15]);
      scratch[(ty * 4u + 3u) * 16u + tx] = t_p;
    }
    workgroupBarrier();
    {
      var t_r = -3.4028234663852886e38;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = max(t_r, scratch[(ty * 4u + 0u) * 16u + t_j]);
      }
      mx[0] = max(mx[0], t_r);
    }
    {
      var t_r = -3.4028234663852886e38;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = max(t_r, scratch[(ty * 4u + 1u) * 16u + t_j]);
      }
      mx[1] = max(mx[1], t_r);
    }
    {
      var t_r = -3.4028234663852886e38;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = max(t_r, scratch[(ty * 4u + 2u) * 16u + t_j]);
      }
      mx[2] = max(mx[2], t_r);
    }
    {
      var t_r = -3.4028234663852886e38;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = max(t_r, scratch[(ty * 4u + 3u) * 16u + t_j]);
      }
      mx[3] = max(mx[3], t_r);
    }
    workgroupBarrier();
  }

  for (var t_cb : u32 = 0u; t_cb < 768u; t_cb = t_cb + 64u) {
    let base_n = t_cb;
    var s : array<f32, 16>;
    s[0] = 0.0;
    s[1] = 0.0;
    s[2] = 0.0;
    s[3] = 0.0;
    s[4] = 0.0;
    s[5] = 0.0;
    s[6] = 0.0;
    s[7] = 0.0;
    s[8] = 0.0;
    s[9] = 0.0;
    s[10] = 0.0;
    s[11] = 0.0;
    s[12] = 0.0;
    s[13] = 0.0;
    s[14] = 0.0;
    s[15] = 0.0;
  for (var t_cb_k : u32 = 0u; t_cb_k < 512u; t_cb_k = t_cb_k + 16u) {
    for (var t_i : u32 = tid; t_i < 1024u; t_i = t_i + 256u) {
      let t_r = t_i / 16u;
      let t_cc = t_i % 16u;
      let t_gr = base_m + t_r;
      let t_gc = t_cb_k + t_cc;
      let off2 = t_gr * 512u + t_gc;
      stage_a[t_i] = a[off2];
    }
    for (var t_i : u32 = tid; t_i < 1024u; t_i = t_i + 256u) {
      let t_r = t_i / 64u;
      let t_cc = t_i % 64u;
      let t_gr = t_cb_k + t_r;
      let t_gc = base_n + t_cc;
      let off3 = t_gr * 768u + t_gc;
      stage_b[t_i] = b[off3];
    }
    workgroupBarrier();

    let t_base_a_0 = (ty * 4u + 0u) * 16u;
    let t_base_a_1 = (ty * 4u + 1u) * 16u;
    let t_base_a_2 = (ty * 4u + 2u) * 16u;
    let t_base_a_3 = (ty * 4u + 3u) * 16u;
    let t_base_b_0 = tx * 4u + 0u;
    let t_base_b_1 = tx * 4u + 1u;
    let t_base_b_2 = tx * 4u + 2u;
    let t_base_b_3 = tx * 4u + 3u;
    for (var t_s : u32 = 0u; t_s < 16u; t_s = t_s + 1u) {
      let t_lc = t_s;
      let t_ci = t_cb_k + t_lc;
        let v_a_0 = stage_a[t_base_a_0 + t_lc];
        let v_a_1 = stage_a[t_base_a_1 + t_lc];
        let v_a_2 = stage_a[t_base_a_2 + t_lc];
        let v_a_3 = stage_a[t_base_a_3 + t_lc];
        let v_b_0 = stage_b[t_lc * 64u + t_base_b_0];
        let v_b_1 = stage_b[t_lc * 64u + t_base_b_1];
        let v_b_2 = stage_b[t_lc * 64u + t_base_b_2];
        let v_b_3 = stage_b[t_lc * 64u + t_base_b_3];
        s[0] = s[0] + v_a_0 * v_b_0;
        s[1] = s[1] + v_a_0 * v_b_1;
        s[2] = s[2] + v_a_0 * v_b_2;
        s[3] = s[3] + v_a_0 * v_b_3;
        s[4] = s[4] + v_a_1 * v_b_0;
        s[5] = s[5] + v_a_1 * v_b_1;
        s[6] = s[6] + v_a_1 * v_b_2;
        s[7] = s[7] + v_a_1 * v_b_3;
        s[8] = s[8] + v_a_2 * v_b_0;
        s[9] = s[9] + v_a_2 * v_b_1;
        s[10] = s[10] + v_a_2 * v_b_2;
        s[11] = s[11] + v_a_2 * v_b_3;
        s[12] = s[12] + v_a_3 * v_b_0;
        s[13] = s[13] + v_a_3 * v_b_1;
        s[14] = s[14] + v_a_3 * v_b_2;
        s[15] = s[15] + v_a_3 * v_b_3;
    }
    workgroupBarrier();
  }

    {
      var t_p = 0.0;
      t_p = t_p + exp((s[0] - mx[0]));
      t_p = t_p + exp((s[1] - mx[0]));
      t_p = t_p + exp((s[2] - mx[0]));
      t_p = t_p + exp((s[3] - mx[0]));
      scratch[(ty * 4u + 0u) * 16u + tx] = t_p;
    }
    {
      var t_p = 0.0;
      t_p = t_p + exp((s[4] - mx[1]));
      t_p = t_p + exp((s[5] - mx[1]));
      t_p = t_p + exp((s[6] - mx[1]));
      t_p = t_p + exp((s[7] - mx[1]));
      scratch[(ty * 4u + 1u) * 16u + tx] = t_p;
    }
    {
      var t_p = 0.0;
      t_p = t_p + exp((s[8] - mx[2]));
      t_p = t_p + exp((s[9] - mx[2]));
      t_p = t_p + exp((s[10] - mx[2]));
      t_p = t_p + exp((s[11] - mx[2]));
      scratch[(ty * 4u + 2u) * 16u + tx] = t_p;
    }
    {
      var t_p = 0.0;
      t_p = t_p + exp((s[12] - mx[3]));
      t_p = t_p + exp((s[13] - mx[3]));
      t_p = t_p + exp((s[14] - mx[3]));
      t_p = t_p + exp((s[15] - mx[3]));
      scratch[(ty * 4u + 3u) * 16u + tx] = t_p;
    }
    workgroupBarrier();
    {
      var t_r = 0.0;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = t_r + scratch[(ty * 4u + 0u) * 16u + t_j];
      }
      sm[0] = sm[0] + t_r;
    }
    {
      var t_r = 0.0;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = t_r + scratch[(ty * 4u + 1u) * 16u + t_j];
      }
      sm[1] = sm[1] + t_r;
    }
    {
      var t_r = 0.0;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = t_r + scratch[(ty * 4u + 2u) * 16u + t_j];
      }
      sm[2] = sm[2] + t_r;
    }
    {
      var t_r = 0.0;
      for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
        t_r = t_r + scratch[(ty * 4u + 3u) * 16u + t_j];
      }
      sm[3] = sm[3] + t_r;
    }
    workgroupBarrier();
  }

  for (var t_cb : u32 = 0u; t_cb < 768u; t_cb = t_cb + 64u) {
    let base_n = t_cb;
    var s : array<f32, 16>;
    s[0] = 0.0;
    s[1] = 0.0;
    s[2] = 0.0;
    s[3] = 0.0;
    s[4] = 0.0;
    s[5] = 0.0;
    s[6] = 0.0;
    s[7] = 0.0;
    s[8] = 0.0;
    s[9] = 0.0;
    s[10] = 0.0;
    s[11] = 0.0;
    s[12] = 0.0;
    s[13] = 0.0;
    s[14] = 0.0;
    s[15] = 0.0;
  for (var t_cb_k : u32 = 0u; t_cb_k < 512u; t_cb_k = t_cb_k + 16u) {
    for (var t_i : u32 = tid; t_i < 1024u; t_i = t_i + 256u) {
      let t_r = t_i / 16u;
      let t_cc = t_i % 16u;
      let t_gr = base_m + t_r;
      let t_gc = t_cb_k + t_cc;
      let off4 = t_gr * 512u + t_gc;
      stage_a[t_i] = a[off4];
    }
    for (var t_i : u32 = tid; t_i < 1024u; t_i = t_i + 256u) {
      let t_r = t_i / 64u;
      let t_cc = t_i % 64u;
      let t_gr = t_cb_k + t_r;
      let t_gc = base_n + t_cc;
      let off5 = t_gr * 768u + t_gc;
      stage_b[t_i] = b[off5];
    }
    workgroupBarrier();

    let t_base_a_0 = (ty * 4u + 0u) * 16u;
    let t_base_a_1 = (ty * 4u + 1u) * 16u;
    let t_base_a_2 = (ty * 4u + 2u) * 16u;
    let t_base_a_3 = (ty * 4u + 3u) * 16u;
    let t_base_b_0 = tx * 4u + 0u;
    let t_base_b_1 = tx * 4u + 1u;
    let t_base_b_2 = tx * 4u + 2u;
    let t_base_b_3 = tx * 4u + 3u;
    for (var t_s : u32 = 0u; t_s < 16u; t_s = t_s + 1u) {
      let t_lc = t_s;
      let t_ci = t_cb_k + t_lc;
        let v_a_0 = stage_a[t_base_a_0 + t_lc];
        let v_a_1 = stage_a[t_base_a_1 + t_lc];
        let v_a_2 = stage_a[t_base_a_2 + t_lc];
        let v_a_3 = stage_a[t_base_a_3 + t_lc];
        let v_b_0 = stage_b[t_lc * 64u + t_base_b_0];
        let v_b_1 = stage_b[t_lc * 64u + t_base_b_1];
        let v_b_2 = stage_b[t_lc * 64u + t_base_b_2];
        let v_b_3 = stage_b[t_lc * 64u + t_base_b_3];
        s[0] = s[0] + v_a_0 * v_b_0;
        s[1] = s[1] + v_a_0 * v_b_1;
        s[2] = s[2] + v_a_0 * v_b_2;
        s[3] = s[3] + v_a_0 * v_b_3;
        s[4] = s[4] + v_a_1 * v_b_0;
        s[5] = s[5] + v_a_1 * v_b_1;
        s[6] = s[6] + v_a_1 * v_b_2;
        s[7] = s[7] + v_a_1 * v_b_3;
        s[8] = s[8] + v_a_2 * v_b_0;
        s[9] = s[9] + v_a_2 * v_b_1;
        s[10] = s[10] + v_a_2 * v_b_2;
        s[11] = s[11] + v_a_2 * v_b_3;
        s[12] = s[12] + v_a_3 * v_b_0;
        s[13] = s[13] + v_a_3 * v_b_1;
        s[14] = s[14] + v_a_3 * v_b_2;
        s[15] = s[15] + v_a_3 * v_b_3;
    }
    workgroupBarrier();
  }

    y[(base_m + ty * 4u + 0u) * 768u + (base_n + tx * 4u + 0u)] = (exp((s[0] - mx[0])) / sm[0]);
    y[(base_m + ty * 4u + 0u) * 768u + (base_n + tx * 4u + 1u)] = (exp((s[1] - mx[0])) / sm[0]);
    y[(base_m + ty * 4u + 0u) * 768u + (base_n + tx * 4u + 2u)] = (exp((s[2] - mx[0])) / sm[0]);
    y[(base_m + ty * 4u + 0u) * 768u + (base_n + tx * 4u + 3u)] = (exp((s[3] - mx[0])) / sm[0]);
    y[(base_m + ty * 4u + 1u) * 768u + (base_n + tx * 4u + 0u)] = (exp((s[4] - mx[1])) / sm[1]);
    y[(base_m + ty * 4u + 1u) * 768u + (base_n + tx * 4u + 1u)] = (exp((s[5] - mx[1])) / sm[1]);
    y[(base_m + ty * 4u + 1u) * 768u + (base_n + tx * 4u + 2u)] = (exp((s[6] - mx[1])) / sm[1]);
    y[(base_m + ty * 4u + 1u) * 768u + (base_n + tx * 4u + 3u)] = (exp((s[7] - mx[1])) / sm[1]);
    y[(base_m + ty * 4u + 2u) * 768u + (base_n + tx * 4u + 0u)] = (exp((s[8] - mx[2])) / sm[2]);
    y[(base_m + ty * 4u + 2u) * 768u + (base_n + tx * 4u + 1u)] = (exp((s[9] - mx[2])) / sm[2]);
    y[(base_m + ty * 4u + 2u) * 768u + (base_n + tx * 4u + 2u)] = (exp((s[10] - mx[2])) / sm[2]);
    y[(base_m + ty * 4u + 2u) * 768u + (base_n + tx * 4u + 3u)] = (exp((s[11] - mx[2])) / sm[2]);
    y[(base_m + ty * 4u + 3u) * 768u + (base_n + tx * 4u + 0u)] = (exp((s[12] - mx[3])) / sm[3]);
    y[(base_m + ty * 4u + 3u) * 768u + (base_n + tx * 4u + 1u)] = (exp((s[13] - mx[3])) / sm[3]);
    y[(base_m + ty * 4u + 3u) * 768u + (base_n + tx * 4u + 2u)] = (exp((s[14] - mx[3])) / sm[3]);
    y[(base_m + ty * 4u + 3u) * 768u + (base_n + tx * 4u + 3u)] = (exp((s[15] - mx[3])) / sm[3]);

  }

}
