// Generated by tessera from a TypeScript kernel. Do not edit.
//
//   softmax_f32: m=1024 x n=750
//   schedule rowwise   workgroup 16x16x1   fragment 4x4
//   masked: x:n y:n   pad negInf (-3.4028234663852886e38)

@group(0) @binding(0) var<storage, read> x : array<f32>;
@group(0) @binding(1) var<storage, read_write> y : array<f32>;

var<workgroup> scratch : array<f32, 1024>;   // rows x lanes

@compute @workgroup_size(16, 16, 1)
fn softmax_f32(@builtin(workgroup_id)        wg  : vec3<u32>,
              @builtin(local_invocation_id) lid : vec3<u32>) {
  let blockRow = wg.x;
  let tx  = lid.x;
  let ty  = lid.y;
  let rowBase = blockRow * 64u;

  var mx : array<f32, 4>;
  mx[0] = -3.4028234663852886e38;
  mx[1] = -3.4028234663852886e38;
  mx[2] = -3.4028234663852886e38;
  mx[3] = -3.4028234663852886e38;
  var sm : array<f32, 4>;
  sm[0] = 0.0;
  sm[1] = 0.0;
  sm[2] = 0.0;
  sm[3] = 0.0;

  for (var nn : u32 = 0u; nn < 750u; nn = nn + 64u) {
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[0] = max(mx[0], v);
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[0] = max(mx[0], v);
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[0] = max(mx[0], v);
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[0] = max(mx[0], v);
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[1] = max(mx[1], v);
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[1] = max(mx[1], v);
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[1] = max(mx[1], v);
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[1] = max(mx[1], v);
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[2] = max(mx[2], v);
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[2] = max(mx[2], v);
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[2] = max(mx[2], v);
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[2] = max(mx[2], v);
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[3] = max(mx[3], v);
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[3] = max(mx[3], v);
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[3] = max(mx[3], v);
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      mx[3] = max(mx[3], v);
    }
  }
  scratch[(ty * 4u + 0u) * 16u + tx] = mx[0];
  scratch[(ty * 4u + 1u) * 16u + tx] = mx[1];
  scratch[(ty * 4u + 2u) * 16u + tx] = mx[2];
  scratch[(ty * 4u + 3u) * 16u + tx] = mx[3];
  workgroupBarrier();
  {
    var r = -3.4028234663852886e38;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = max(r, scratch[(ty * 4u + 0u) * 16u + j]);
    }
    mx[0] = r;
  }
  {
    var r = -3.4028234663852886e38;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = max(r, scratch[(ty * 4u + 1u) * 16u + j]);
    }
    mx[1] = r;
  }
  {
    var r = -3.4028234663852886e38;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = max(r, scratch[(ty * 4u + 2u) * 16u + j]);
    }
    mx[2] = r;
  }
  {
    var r = -3.4028234663852886e38;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = max(r, scratch[(ty * 4u + 3u) * 16u + j]);
    }
    mx[3] = r;
  }
  workgroupBarrier();

  for (var nn : u32 = 0u; nn < 750u; nn = nn + 64u) {
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[0] = sm[0] + exp((v - mx[0]));
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[0] = sm[0] + exp((v - mx[0]));
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[0] = sm[0] + exp((v - mx[0]));
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[0] = sm[0] + exp((v - mx[0]));
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[1] = sm[1] + exp((v - mx[1]));
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[1] = sm[1] + exp((v - mx[1]));
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[1] = sm[1] + exp((v - mx[1]));
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[1] = sm[1] + exp((v - mx[1]));
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[2] = sm[2] + exp((v - mx[2]));
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[2] = sm[2] + exp((v - mx[2]));
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[2] = sm[2] + exp((v - mx[2]));
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[2] = sm[2] + exp((v - mx[2]));
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[3] = sm[3] + exp((v - mx[3]));
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[3] = sm[3] + exp((v - mx[3]));
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[3] = sm[3] + exp((v - mx[3]));
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      sm[3] = sm[3] + exp((v - mx[3]));
    }
  }
  scratch[(ty * 4u + 0u) * 16u + tx] = sm[0];
  scratch[(ty * 4u + 1u) * 16u + tx] = sm[1];
  scratch[(ty * 4u + 2u) * 16u + tx] = sm[2];
  scratch[(ty * 4u + 3u) * 16u + tx] = sm[3];
  workgroupBarrier();
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 0u) * 16u + j];
    }
    sm[0] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 1u) * 16u + j];
    }
    sm[1] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 2u) * 16u + j];
    }
    sm[2] = r;
  }
  {
    var r = 0.0;
    for (var j : u32 = 0u; j < 16u; j = j + 1u) {
      r = r + scratch[(ty * 4u + 3u) * 16u + j];
    }
    sm[3] = r;
  }
  workgroupBarrier();

  for (var nn : u32 = 0u; nn < 750u; nn = nn + 64u) {
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[0])) / sm[0]);
      }
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[0])) / sm[0]);
      }
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[0])) / sm[0]);
      }
    }
    {
      let row = rowBase + ty * 4u + 0u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[0])) / sm[0]);
      }
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[1])) / sm[1]);
      }
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[1])) / sm[1]);
      }
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[1])) / sm[1]);
      }
    }
    {
      let row = rowBase + ty * 4u + 1u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[1])) / sm[1]);
      }
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[2])) / sm[2]);
      }
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[2])) / sm[2]);
      }
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[2])) / sm[2]);
      }
    }
    {
      let row = rowBase + ty * 4u + 2u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[2])) / sm[2]);
      }
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 0u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[3])) / sm[3]);
      }
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 1u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[3])) / sm[3]);
      }
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 2u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[3])) / sm[3]);
      }
    }
    {
      let row = rowBase + ty * 4u + 3u;
      let col = nn + tx * 4u + 3u;
      let off = row * 750u + col;
      let v = select(-3.4028234663852886e38, x[min(off, 767999u)], col < 750u);
      if (col < 750u) {
        y[row * 750u + col] = (exp((v - mx[3])) / sm[3]);
      }
    }
  }

}
