// Generated by tessera from a TypeScript kernel. Do not edit.
//
//   softmax_f32   accumulate (m)   contract n
//   lanes m->y(4)  n->x   fragment 4   4 sequential steps
//   staged: nothing — no operand is reused   workgroup 4096 B
//   masked: x:n y:n   pad negInf (-3.4028234663852886e38)

@group(0) @binding(0) var<storage, read> x : array<f32>;
@group(0) @binding(1) var<storage, read_write> y : array<f32>;

var<workgroup> scratch : array<f32, 1024>;   // fragment x lanes

@compute @workgroup_size(16, 16, 1)
fn softmax_f32(@builtin(workgroup_id)        wg  : vec3<u32>,
              @builtin(local_invocation_id) lid : vec3<u32>) {
  let tx = lid.x;
  let ty = lid.y;
  let tid = ty * 16u + tx;
  let base_m = wg.x * 64u;

  var mx : array<f32, 4>;
  mx[0] = -3.4028234663852886e38;
  mx[1] = -3.4028234663852886e38;
  mx[2] = -3.4028234663852886e38;
  mx[3] = -3.4028234663852886e38;
  var sm : array<f32, 4>;
  sm[0] = 0.0;
  sm[1] = 0.0;
  sm[2] = 0.0;
  sm[3] = 0.0;

  for (var t_cb : u32 = 0u; t_cb < 750u; t_cb = t_cb + 64u) {
    for (var t_s : u32 = 0u; t_s < 4u; t_s = t_s + 1u) {
      let t_lc = tx * 4u + t_s;
      let t_ci = t_cb + t_lc;
        let off0 = (base_m + ty * 4u + 0u) * 750u + (t_ci);
        let v_x_0 = select(-3.4028234663852886e38, x[min(off0, 767999u)], (t_ci) < 750u);
        let off1 = (base_m + ty * 4u + 1u) * 750u + (t_ci);
        let v_x_1 = select(-3.4028234663852886e38, x[min(off1, 767999u)], (t_ci) < 750u);
        let off2 = (base_m + ty * 4u + 2u) * 750u + (t_ci);
        let v_x_2 = select(-3.4028234663852886e38, x[min(off2, 767999u)], (t_ci) < 750u);
        let off3 = (base_m + ty * 4u + 3u) * 750u + (t_ci);
        let v_x_3 = select(-3.4028234663852886e38, x[min(off3, 767999u)], (t_ci) < 750u);
        mx[0] = max(mx[0], v_x_0);
        mx[1] = max(mx[1], v_x_1);
        mx[2] = max(mx[2], v_x_2);
        mx[3] = max(mx[3], v_x_3);
    }
  }

  scratch[(ty * 4u + 0u) * 16u + tx] = mx[0];
  scratch[(ty * 4u + 1u) * 16u + tx] = mx[1];
  scratch[(ty * 4u + 2u) * 16u + tx] = mx[2];
  scratch[(ty * 4u + 3u) * 16u + tx] = mx[3];
  workgroupBarrier();
  {
    var t_r = -3.4028234663852886e38;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = max(t_r, scratch[(ty * 4u + 0u) * 16u + t_j]);
    }
    mx[0] = t_r;
  }
  {
    var t_r = -3.4028234663852886e38;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = max(t_r, scratch[(ty * 4u + 1u) * 16u + t_j]);
    }
    mx[1] = t_r;
  }
  {
    var t_r = -3.4028234663852886e38;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = max(t_r, scratch[(ty * 4u + 2u) * 16u + t_j]);
    }
    mx[2] = t_r;
  }
  {
    var t_r = -3.4028234663852886e38;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = max(t_r, scratch[(ty * 4u + 3u) * 16u + t_j]);
    }
    mx[3] = t_r;
  }
  workgroupBarrier();

  for (var t_cb : u32 = 0u; t_cb < 750u; t_cb = t_cb + 64u) {
    for (var t_s : u32 = 0u; t_s < 4u; t_s = t_s + 1u) {
      let t_lc = tx * 4u + t_s;
      let t_ci = t_cb + t_lc;
        let off4 = (base_m + ty * 4u + 0u) * 750u + (t_ci);
        let v_x_0 = select(-3.4028234663852886e38, x[min(off4, 767999u)], (t_ci) < 750u);
        let off5 = (base_m + ty * 4u + 1u) * 750u + (t_ci);
        let v_x_1 = select(-3.4028234663852886e38, x[min(off5, 767999u)], (t_ci) < 750u);
        let off6 = (base_m + ty * 4u + 2u) * 750u + (t_ci);
        let v_x_2 = select(-3.4028234663852886e38, x[min(off6, 767999u)], (t_ci) < 750u);
        let off7 = (base_m + ty * 4u + 3u) * 750u + (t_ci);
        let v_x_3 = select(-3.4028234663852886e38, x[min(off7, 767999u)], (t_ci) < 750u);
        sm[0] = sm[0] + exp((v_x_0 - mx[0]));
        sm[1] = sm[1] + exp((v_x_1 - mx[1]));
        sm[2] = sm[2] + exp((v_x_2 - mx[2]));
        sm[3] = sm[3] + exp((v_x_3 - mx[3]));
    }
  }

  scratch[(ty * 4u + 0u) * 16u + tx] = sm[0];
  scratch[(ty * 4u + 1u) * 16u + tx] = sm[1];
  scratch[(ty * 4u + 2u) * 16u + tx] = sm[2];
  scratch[(ty * 4u + 3u) * 16u + tx] = sm[3];
  workgroupBarrier();
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 0u) * 16u + t_j];
    }
    sm[0] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 1u) * 16u + t_j];
    }
    sm[1] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 2u) * 16u + t_j];
    }
    sm[2] = t_r;
  }
  {
    var t_r = 0.0;
    for (var t_j : u32 = 0u; t_j < 16u; t_j = t_j + 1u) {
      t_r = t_r + scratch[(ty * 4u + 3u) * 16u + t_j];
    }
    sm[3] = t_r;
  }
  workgroupBarrier();

  for (var t_cb : u32 = 0u; t_cb < 750u; t_cb = t_cb + 64u) {
    for (var t_s : u32 = 0u; t_s < 4u; t_s = t_s + 1u) {
      let t_lc = tx * 4u + t_s;
      let t_ci = t_cb + t_lc;
        let off8 = (base_m + ty * 4u + 0u) * 750u + (t_ci);
        let v_x_0 = select(-3.4028234663852886e38, x[min(off8, 767999u)], (t_ci) < 750u);
        let off9 = (base_m + ty * 4u + 1u) * 750u + (t_ci);
        let v_x_1 = select(-3.4028234663852886e38, x[min(off9, 767999u)], (t_ci) < 750u);
        let off10 = (base_m + ty * 4u + 2u) * 750u + (t_ci);
        let v_x_2 = select(-3.4028234663852886e38, x[min(off10, 767999u)], (t_ci) < 750u);
        let off11 = (base_m + ty * 4u + 3u) * 750u + (t_ci);
        let v_x_3 = select(-3.4028234663852886e38, x[min(off11, 767999u)], (t_ci) < 750u);
        if ((t_ci) < 750u) {
          y[(base_m + ty * 4u + 0u) * 750u + (t_ci)] = (exp((v_x_0 - mx[0])) / sm[0]);
        }
        if ((t_ci) < 750u) {
          y[(base_m + ty * 4u + 1u) * 750u + (t_ci)] = (exp((v_x_1 - mx[1])) / sm[1]);
        }
        if ((t_ci) < 750u) {
          y[(base_m + ty * 4u + 2u) * 750u + (t_ci)] = (exp((v_x_2 - mx[2])) / sm[2]);
        }
        if ((t_ci) < 750u) {
          y[(base_m + ty * 4u + 3u) * 750u + (t_ci)] = (exp((v_x_3 - mx[3])) / sm[3]);
        }
    }
  }
}
