/**
 * emit-wgsl.ts — tessera IR straight to WGSL, bypassing MLIR entirely.
 *
 * This is the A/B that settles docs/002 §4. The MLIR path crosses four
 * translation boundaries the hand-written kernel does not
 * (IR → MLIR → SPIR-V → naga → WGSL), and by elimination that is the remaining
 * candidate for the 1.57× gap: three hypotheses about tessera making worse
 * codegen choices were each probed and refuted.
 *
 * For the comparison to mean anything, this backend must make the SAME decisions
 * as the MLIR one and differ ONLY in how it emits them. So it deliberately
 * mirrors emit-mlir.ts: same tile, same fragment layout, same staging loop
 * structure, same clamp-and-select for masked loads, same conditional store, the
 * same rolled k loop. Anything that differs here is a confound, not a result.
 *
 * Two differences are unavoidable and are the point:
 *   - loops come out structured, because WGSL is structured, where the MLIR path
 *     goes through an unstructured IR and naga reconstructs `loop{}/continuing{}`
 *   - storage access modes are `read` where the surface says `read`, because the
 *     IR knows the binding mode. The MLIR path drops that on the floor.
 *     (Probe A measured access mode at 1.00×, so this is not a confound.)
 *
 * It is also the third oracle. With three backends agreeing bit-for-bit, a future
 * divergence localises to one of them in a single comparison instead of a
 * twelve-pass bisection.
 */

import { PAD_LITERAL, type AxisIR, type KernelIR } from "./ir.ts";

export function emitWGSL(k: KernelIR): string {
  const { bm, bn, bk } = k.tile;
  const [wgx, wgy] = k.workgroup;
  const [tm, tn] = k.fragment;
  const threads = wgx * wgy;
  const nacc = tm * tn;
  const ty = k.dtype;

  const [gm, gn] = k.grid;
  const rk = k.reduce[0];
  const ragged = (a: AxisIR) => a.fit === "ragged";
  /** The masked-load fill, by name. `zero` is not the only possibility. */
  const PAD = PAD_LITERAL[k.pad];

  const extent = new Map([...k.grid, ...k.reduce].map((a) => [a.name, a.extent]));
  const pick = (mode: "read" | "write", i: number) => k.bindings.filter((b) => b.mode === mode)[i];
  const a = pick("read", 0), b = pick("read", 1), c = pick("write", 0);
  const stride = (x: typeof a) => extent.get(x.axes[1])!;

  const L: string[] = [];
  const P = (s = "", i = 0) => L.push(s ? "  ".repeat(i) + s : "");
  const u = (n: number) => `${n}u`;

  P(`// Generated by tessera from a TypeScript kernel. Do not edit.`);
  P(`//`);
  P(`//   ${k.name}: ${k.grid.map((x) => `${x.name}=${x.extent}`).join(" x ")} x ${rk.name}=${rk.extent}`);
  P(`//   tile ${bm}x${bn}x${bk}   workgroup ${wgx}x${wgy}x1   fragment ${tm}x${tn}`);
  P(`//   ${k.maskedLoads.length ? `masked: ${k.maskedLoads.join(" ")}   pad ${k.pad} (${PAD})` : "no masks: every axis divides its block"}`);
  P();

  // ---- bindings ------------------------------------------------------------
  // The access mode comes from the surface. `input()` is read-only and says so.
  for (const [i, bd] of k.bindings.entries()) {
    const mode = bd.mode === "read" ? "read" : "read_write";
    P(`@group(0) @binding(${i}) var<storage, ${mode}> ${bd.name} : array<${ty}>;`);
  }
  P();
  P(`var<workgroup> As : array<${ty}, ${bm * bk}>;`);
  P(`var<workgroup> Bs : array<${ty}, ${bk * bn}>;`);
  P();

  P(`@compute @workgroup_size(${wgx}, ${wgy}, 1)`);
  P(`fn ${k.name}(@builtin(workgroup_id)        wg  : vec3<u32>,`);
  P(`${" ".repeat(k.name.length + 3)}@builtin(local_invocation_id) lid : vec3<u32>) {`);

  P(`let blockRow = wg.y;`, 1);
  P(`let blockCol = wg.x;`, 1);
  P(`let tx  = lid.x;`, 1);
  P(`let ty  = lid.y;`, 1);
  P(`let tid = ty * ${u(wgx)} + tx;`, 1);
  P(`let rowBase = blockRow * ${u(bm)};`, 1);
  P(`let colBase = blockCol * ${u(bn)};`, 1);
  P();
  P(`var acc : array<${ty}, ${nacc}>;`, 1);
  P();

  // ---- reduction over blocks ----------------------------------------------
  P(`for (var kk : u32 = 0u; kk < ${u(rk.extent)}; kk = kk + ${u(bk)}) {`, 1);

  // stage A
  P(`for (var i : u32 = tid; i < ${u(bm * bk)}; i = i + ${u(threads)}) {`, 2);
  P(`let r  = i / ${u(bk)};`, 3);
  P(`let cc = i % ${u(bk)};`, 3);
  P(`let gr = rowBase + r;`, 3);
  P(`let gc = kk + cc;`, 3);
  P(`let off = gr * ${u(stride(a))} + gc;`, 3);
  if (ragged(gm) || ragged(rk)) {
    const conds = [
      ...(ragged(gm) ? [`gr < ${u(gm.extent)}`] : []),
      ...(ragged(rk) ? [`gc < ${u(rk.extent)}`] : []),
    ];
    // Clamp then select: branchless, and identical in meaning to what the MLIR
    // backend emits. A branch would diverge for exactly one block per row.
    P(`As[i] = select(${PAD}, ${a.name}[min(off, ${u(a.elements - 1)})], ${conds.join(" && ")});`, 3);
  } else {
    P(`As[i] = ${a.name}[off];`, 3);
  }
  P(`}`, 2);

  // stage B
  P(`for (var i : u32 = tid; i < ${u(bk * bn)}; i = i + ${u(threads)}) {`, 2);
  P(`let r  = i / ${u(bn)};`, 3);
  P(`let cc = i % ${u(bn)};`, 3);
  P(`let gr = kk + r;`, 3);
  P(`let gc = colBase + cc;`, 3);
  P(`let off = gr * ${u(stride(b))} + gc;`, 3);
  if (ragged(rk) || ragged(gn)) {
    const conds = [
      ...(ragged(rk) ? [`gr < ${u(rk.extent)}`] : []),
      ...(ragged(gn) ? [`gc < ${u(gn.extent)}`] : []),
    ];
    P(`Bs[i] = select(${PAD}, ${b.name}[min(off, ${u(b.elements - 1)})], ${conds.join(" && ")});`, 3);
  } else {
    P(`Bs[i] = ${b.name}[off];`, 3);
  }
  P(`}`, 2);

  P(`workgroupBarrier();`, 2);
  P();

  // ---- accumulate ----------------------------------------------------------
  P(`for (var k : u32 = 0u; k < ${u(bk)}; k = k + 1u) {`, 2);
  for (let m = 0; m < tm; m++) {
    P(`let af${m} = As[(ty * ${u(tm)} + ${u(m)}) * ${u(bk)} + k];`, 3);
  }
  for (let n = 0; n < tn; n++) {
    P(`let bf${n} = Bs[k * ${u(bn)} + (tx * ${u(tn)} + ${u(n)})];`, 3);
  }
  for (let m = 0; m < tm; m++) {
    for (let n = 0; n < tn; n++) {
      const i = m * tn + n;
      P(`acc[${i}] = acc[${i}] + af${m} * bf${n};`, 3);
    }
  }
  P(`}`, 2);

  P();
  P(`workgroupBarrier();`, 2);
  P(`}`, 1);
  P();

  // ---- relu + store --------------------------------------------------------
  for (let m = 0; m < tm; m++) {
    P(`let row${m} = rowBase + ty * ${u(tm)} + ${u(m)};`, 1);
    for (let n = 0; n < tn; n++) {
      const i = m * tn + n;
      P(`let col${i} = colBase + tx * ${u(tn)} + ${u(n)};`, 1);
      // relu as a comparison + select, matching the MLIR backend exactly:
      // `max()` there lowered with NaN-propagating semantics that naga rejects,
      // and this form is also what the CPU oracle computes.
      const val = `select(0.0, acc[${i}], acc[${i}] > 0.0)`;
      if (ragged(gm) || ragged(gn)) {
        const conds = [
          ...(ragged(gm) ? [`row${m} < ${u(gm.extent)}`] : []),
          ...(ragged(gn) ? [`col${i} < ${u(gn.extent)}`] : []),
        ];
        // A store cannot be clamped — a legal-but-wrong address corrupts a real
        // element — so this one is a genuine conditional in both backends.
        P(`if (${conds.join(" && ")}) {`, 1);
        P(`${c.name}[row${m} * ${u(stride(c))} + col${i}] = ${val};`, 2);
        P(`}`, 1);
      } else {
        P(`${c.name}[row${m} * ${u(stride(c))} + col${i}] = ${val};`, 1);
      }
    }
  }

  P(`}`);
  return L.join("\n") + "\n";
}
