// GENERATED by `npx tessera gen` -- do not edit.
// All integer arithmetic runs ONCE here, in ordinary JavaScript, and is frozen
// into interfaces that tsc answers by property lookup. No type-level arithmetic.

export type Block = 8 | 16 | 32 | 64 | 128;

/**
 * TileFit[bytesPerElement][BM][BN] -> the BK values for which
 *   (BM*BK + BK*BN) * bytes <= 12288
 * 12288 = 16384 (WebGPU maxComputeWorkgroupStorageSize floor) - 4096 reserved
 * for double-buffering / bank-conflict padding / compiler scratch.
 */
export interface TileFit {
  4: {
    32: { 32: 8 | 16 | 32; 64: 8 | 16 | 32; 128: 8 | 16 };
    64: { 32: 8 | 16 | 32; 64: 8 | 16; 128: 8 | 16 };
    128: { 32: 8 | 16; 64: 8 | 16; 128: 8 };
  };
  2: {
    32: { 32: 8 | 16 | 32 | 64; 64: 8 | 16 | 32 | 64; 128: 8 | 16 | 32 };
    64: { 32: 8 | 16 | 32 | 64; 64: 8 | 16 | 32; 128: 8 | 16 | 32 };
    128: { 32: 8 | 16 | 32; 64: 8 | 16 | 32; 128: 8 | 16 };
  };
}

/** x*y*z <= 256, x <= 256, y <= 256, z <= 64. Pre-validated, enumerated. */
export type WorkgroupShape =
  | readonly [64, 1, 1]
  | readonly [128, 1, 1]
  | readonly [256, 1, 1]
  | readonly [8, 8, 1]
  | readonly [16, 8, 1]
  | readonly [16, 16, 1]
  | readonly [32, 8, 1];
